---
# true / false

# {server_name} - имя сервера
# {player_name} - имя игрока
# {online} - текущий онлайн сервера
# {max} - максимальный онлайн сервера

server_name: "§7<имя сервера>§r"

# Шифрование паролей
password_encrypt:
  enable: true
  key: "usersPluginHashSalt"

# Ограничений регистраций с одного адреса
accounts_limit:
  enable: true
  limit: 2
  message: "Не более %l аккаунтов на один IP-адрес"
# %l - лимит

# Приветствие на экране
welcome_title:
  enable: true
  title: "{server_name}"
  subtitle: "{online}/{max}"
  fadein: 1
  fadeout: 1
  duration: 1

# Приветствие в чате
welcome_message:
  enable: true
  message: "Вы уже вводили пароль. Приятной игры!"

# Уведомление о новом игроке
new_player:
  enable: true
  message: "§a%p §rвпервые зашёл(а) на наш сервер! §7[§c#%c§7]"
# %p - имя игрока
# %c - новый игрок по счёту

# Регистрация
register: "Приветствуем на сервере {server_name}. Вы зашли впервые, для регистрации введите пароль в §aчат§r."

# Вход
login: "Приветствуем на сервере {server_name}. Для входа введите пароль в §aчат§r."

# Успешный вход
login_success: "Вы вошли в аккаунт. Приятной игры!"

# Успешная регистрация
register_success: "Вы зарегистрировались на сервере. Ваш пароль: §a%p§r. Приятной игры!"
# %p - пароль

# Неверный пароль
invalid_password: "§cНеверный пароль."
invalid_password_last: "§cОсталось попыток: "

# Запрещённые символы в пароле
invalid_symbols: "§cРазрешены только английские буквы, цифры и специальные символы."

# Короткий пароль
password_len: "§cПароль должен быть не менее 5 символов."

# Введите пароль
enter_password: "Введите пароль в §aчат"

# Выполнение команды
deprecate_commands: "§cАвторизируйтесь, чтобы использовать команды."

# Выход из аккаунта
logout: "§aВы вышли из аккаунта."

# Смена пароля
password_change: "Вы успешно сменили пароль."

# Ввод пароля в чат
password_chat: "§aВаш пароль был скрыт. Никому не сообщайте его!"

# Тайм-аут входа
not_logined: "§cВы не вошли на сервер в течение 1 минуты."
...
