---
#Ключ шифрования паролей, рекомендуется сменить
key: "passwordHashSalt"

register: "§rПриветствуем на сервере §7<имя сервера>§f. Вы зашли впервые, для регистрации введите пароль в §aчат§f."
login: "§rПриветствуем на сервере §7<имя сервера>§f. Для входа введите пароль в §aчат§f."
login_success: "§rВы вошли в аккаунт. Приятной игры!"
register_success: "§rВы зарегистрировались на сервере. Ваш пароль: §a%p§r. Приятной игры!"
invalid_password: "§r§cНеверный пароль."
invalid_symbols: "§r§cРазрешены только английские буквы, цифры и специальные символы."
password_len: "§r§cПароль должен быть не менее 5 символов."
invalid_password_last: "§r§cОсталось попыток: "
enter_password: "§rВведите пароль в §aчат"
deprecate_commands: "§r§cАвторизируйтесь, чтобы использовать команды."
new_player: "§r§a%p §fвпервые зашёл(а) на наш сервер! §7[§c#%c§7]"
logout: "§r§aВы вышли из аккаунта."
welcome: "§rДобро пожаловать"
server_name: "§r§7<имя сервера>"
password_change: "§rВы успешно сменили пароль."
password_chat: "§r§aВаш пароль был скрыт. Никому не сообщайте его!"
not_logined: "§r§cВы не вошли на сервер в течение 1 минуты."
...
